### ISSUE TITLE
After Steps, I can't start my project. 

### ISSUE THREAD

**Issue by JinYu1998** [argmaxinc/WhisperKit#19]
1. I created a new project in xcode, named WhisperKit.
2. I added WhisperKit according to the steps.
3. I added the following code to WhisperKit/WhisperKit/WhisperKitApp

```swift

import SwiftUI
import WhisperKit

@main
struct WhisperKitApp: App {
    init() {
        Task {
            do {
                let pipe = try? await WhisperKit()
                let transcription = try? await pipe!.transcribe(audioPath: "Audio/output-lang.wav")?.text
                print(transcription)
            } catch {
                print("Error: \(error)")
            }
        }
    }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

Then I get an error : `Cannot call value of non-function type 'module<WhisperKit>'`

What should I do to solve this problem? tks.

**Comment by ZachNagengast** [comment]
Following up from this [thread](https://discord.com/channels/1171912382512115722/1201632745068167369/1206613897792987156) in discord, there appears to be a naming conflict in your app where something is already using the name `WhisperKit` so importing it is ineffective. I recommend trying to find the naming conflict in your project and using a different name so that the `WhisperKit` swift package can be imported. At that point, you may want to consider moving the initialization into your ContentView or some view model class so it can be managed more easily within your app.

**Comment by ZachNagengast** [comment]
Looks like this was resolved:  https://discord.com/channels/1171912382512115722/1201632730446823444/1206875382712635432
