### ISSUE TITLE
Unable to download the model

### ISSUE THREAD

**Issue by Srinarayan002** [argmaxinc/WhisperKit#266]
When I run the code :let pipe = try? await WhisperKit(WhisperKitConfig(model: "large-v3")) I get the following error
Is there something which I am missing
NSErrorFailingURLStringKey=https://huggingface.co/api/models/argmaxinc/whisperkit-coreml

**Comment by atiorh** [comment]
Hi @Srinarayan002, can you try to reproduce it? It might be an intermittent network issue.

**Comment by Srinarayan002** [comment]
I got the following error
Model not found. Please check the model or repo name and try again.
Error: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=-72000, NSUnderlyingError=0x6000019c40f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorDomainKey=10, _kCFStreamErrorCodeKey=-72000, _NSURLErrorNWResolutionReportKey=Resolved 0 endpoints in 0ms using unknown from query, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <92D200CC-0BEC-49AA-8935-BB8E4A0DBC79>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <92D200CC-0BEC-49AA-8935-BB8E4A0DBC79>.<2>"
), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://huggingface.co/api/models/argmaxinc/whisperkit-coreml, NSErrorFailingURLKey=https://huggingface.co/api/models/argmaxinc/whisperkit-coreml, _kCFStreamErrorDomainKey=10}

**Comment by ZachNagengast** [comment]
Is this url accessible in your browser? [huggingface.co/api/models/argmaxinc/whisperkit-coreml](https://huggingface.co/api/models/argmaxinc/whisperkit-coreml). One common issue I've seen is not allowing sandbox internet access on a macOS app while developing. You can enable it in Targets > Signing & Capabilities > App Sandbox and making sure these are checked. 
<img width="728" alt="image" src="https://github.com/user-attachments/assets/a3f1dec5-7cef-4005-8f60-e8c8410e399c">

If not then your network may be blocking access to huggingface (or huggingface had an outage at the time of your testing), which is where the models are currently hosted. You would need to manage the models directly in your app otherwise.

**Comment by rudrankriyam** [comment]
I had faced a similar issue and it was due to the App Sandbox as @ZachNagengast mentioned.
