### ISSUE TITLE
Implement async batch predictions

### ISSUE THREAD

**Issue by atiorh** [argmaxinc/WhisperKit#97]
Adopting Core ML's async batch prediction APIs will be crucial for high-throughput batch transcription with WhisperKit.

Reference: https://developer.apple.com/videos/play/wwdc2023/10049/

**Comment by ZachNagengast** [comment]
@jkrukowski has expressed interest in taking this on, here is a suggested approach:

Starting with CLI:
- `--audio-path` accepts an array of audio files now
- `--batch-size` param which stands for maximum concurrent inference that can happen in the queue (default is unlimited). Open to suggestions on terminology, because `batch` isn't exactly the same concept as concurrent async
- Accuracy is within 1%, should not need to tradeoff here (whisperkittools can run this analysis)
- This code may help for reference https://github.com/ZachNagengast/similarity-search-kit/blob/ef737c4aad3af904a9925c476dc37c0dddc6ad8c/Sources/SimilaritySearchKit/Core/Index/SimilarityIndex.swift#L231-L244
